server:
  port: 8088

spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:resources/demo/mapper/xml/*.xml
  #属性为true来开启驼峰功能
  configuration:
    map-underscore-to-camel-case: true
